apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-server-deployment-${VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-server
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: ui-server
        version: ${VERSION}
    spec:
      containers:
      - name: ui-server-container
        imagePullPolicy: Always
        image: ninjaonions/uiserver:${VERSION}
        env:
          - name: VERSION
            value: ${VERSION}
          - name: UI_SERVER_PORT
            value: "31001"
          - name: URL_SERVER_PORT
            value: "31000"
          - name: UI_SERVER_ALIAS
            value: url-server-service
